ALTER TABLE USER_ACCOUNT
    DROP CONSTRAINT UNIQUE_FIRSTNAME_CONSTRAINT;

ALTER TABLE USER_ACCOUNT
    DROP CONSTRAINT UNIQUE_LASTNAME_CONSTRAINT;

ALTER TABLE USER_ACCOUNT
    ADD CONSTRAINT UNIQUE_FULL_NAME_CONSTRAINT UNIQUE (FIRSTNAME, LASTNAME);